
export enum Role {
  FATHER = 'Padre',
  MOTHER = 'Madre',
  CHILD = 'Hijo/a',
  TUTOR = 'Tutor'
}

export enum FamilyStatus {
  ACTIVE = 'Activo',
  INACTIVE = 'Baja'
}

export enum AppRole {
  SUPERADMIN = 'SUPERADMIN',
  ADMIN = 'ADMIN',
  USER = 'USER'
}

export interface User {
  username: string;
  name: string;
  role: AppRole;
}

export interface Member {
  id: string;
  firstName: string;
  lastName: string;
  birthDate: string; // YYYY-MM-DD
  role: Role;
  gender?: string;
  notes?: string;
  email?: string;
  phone?: string;
}

export interface Family {
  id: string;
  membershipNumber: string;
  familyName: string; // e.g., "Familia Pérez García"
  address: string;
  phone: string;
  email: string;
  joinDate: string;
  status: FamilyStatus;
  members: Member[];
  aiSummary?: string; // Generated by Gemini
  createdAt?: string; // ISO String with time
  createdBy?: string; // Username
}

export type ViewState = 'dashboard' | 'list' | 'form' | 'details' | 'config';
